### ISSUE TITLE
Docker problem

### ISSUE THREAD

**Issue by Pitel** [numberly/mattermost-integration-giphy#23] opened 2017-05-26 11:09 UTC
I'm trying to run it with docker, but it doesn't work:
```
➜ curl -v 127.0.0.1:5000/ 
* About to connect() to 127.0.0.1 port 5000 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 5000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:5000
> Accept: */*
> 
------- it just hangs there --------
^C
```

The same with `curl -v 127.0.0.1:5000/new_post`

But it fails when I try different port, so it obviously somehow runs.

I have this in mattermost log:
```
2017-05-26_10:57:15.47724 [2017/05/26 12:57:15 CEST] [EROR] /api/v3/teams/xxxxx/commands/execute:command code=500 rid=xxxxx uid=xxxxx ip=x.x.x.x Command with a trigger of 'giphy' failed [details: Post http://127.0.0.1:5000/new_post: read tcp 127.0.0.1:50494->127.0.0.1:5000: read: connection reset by peer]
```

Some other relevant info:
```
➜ docker ps 
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS              PORTS                    NAMES
d55df86848cd        mattermost-integration-giphy   "python run.py"     14 minutes ago      Up 14 minutes       0.0.0.0:5000->5000/tcp   mattermost-giphy
```
```
➜ docker logs d55df86848cd
[2017-05-26 10:52:49,061] [INFO]  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

**Comment by pichouk** [comment] 2017-05-26 13:09
Can you give the docker command/docker-compose you use to run your Docker container please ?
Did you use a reverse proxy or something else in front of your container ?

**Comment by Pitel** [comment] 2017-05-26 13:31
```
docker run -d --name mattermost-giphy -p 5000:5000 -e MATTERMOST_GIPHY_TOKEN=xxxxxxx -e GIPHY_API_KEY=dc6zaTOxFJmzC mattermost-integration-giphy
```

It runs on the same machine as mattermost. And I figured it's `iptables` problem, because when I disabled them, it works. So now I'm trying to figure out the right configuration...

**Comment by pichouk** [comment] 2017-05-26 13:35
Port 5000 should be open on TCP on your machine. What is configured on iptables ? (`iptables -L` or the script you use to configure iptables on your machine)

**Comment by Pitel** [comment] 2017-05-26 13:42
Those 2 rules solved it (CentOS)
```
➜  ~ sudo iptables -A INPUT -i docker0 -p tcp -m tcp --sport 5000 -j ACCEPT
➜  ~ sudo iptables -A OUTPUT -p tcp -m tcp --dport 5000 -j ACCEPT
```

**Comment by Pitel** [comment] 2017-05-26 13:46
Now in Mattermost, I'm getting:
>/giphy hello
>No gif url found for `hello`

Do you know why, or should I open another issue for it?

**Comment by Pitel** [comment] 2017-05-26 13:48
```
[2017-05-26 13:44:44,914] [ERROR] unable to translate giphy :: HTTPSConnectionPool(host='api.giphy.com', port=443): Max retries exceeded with url: /v1/gifs/translate?rating=pg&s=dickbutt&api_key=dc6zaTOxFJmzC (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2cd6793a90>: Failed to establish a new connection: [Errno -3] Try again',))
```
Probably firewall again :/

**Comment by pichouk** [comment] 2017-05-26 13:50
Your machine should allow your container to made HTTP/S request (TCP port 80 and 443 on OUTPUT)

**Comment by Pitel** [comment] 2017-05-26 13:56
Nope, not firewall this time. It fails even when I disable it:
```
Chain INPUT (policy ACCEPT 2105 packets, 362K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 8 packets, 472 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 1849 packets, 577K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           tcp dpt:5000

Chain DOCKER-ISOLATION (0 references)
 pkts bytes target     prot opt in     out     source               destination         
 376K 2103M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain f2b-SSH (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```

And when I use from the machine
```
curl -v https://api.giphy.com/v1/gifs/translate\?rating\=pg\&s\=bla\&api_key\=dc6zaTOxFJmzC
```
I get some valid response.

**Comment by pichouk** [comment] 2017-05-26 21:21
I cannot reproduce this issue, I just build the image and it works perfectly on my server.

If you want to debug more you can edit your Dockerfile like this :
```
FROM python:2.7

RUN apt-get update && apt-get install curl

COPY . /mattermost-giphy
WORKDIR /mattermost-giphy

RUN python setup.py install

ENTRYPOINT ["python", "run.py"]
```

Then build this image and run your container with it. You should be able to get a shell inside the running container with :
```
docker exec -it mattermost-giphy /bin/bash
```
And you can try to curl from inside the container. Not sure it will help but I have no idea how to reproduce this.

**Comment by ramnes** [comment] 2017-06-22 14:05
@Pitel did you find a way to make it work?

**Comment by pichouk** [comment] 2017-09-22 14:15
Think this issue can be closed.

**Comment by ramnes** [comment] 2017-09-22 17:50
Yeah, closing it. Feel free to reopen if needed.

**Closed as completed by ramnes** 2017-09-22 17:50 UTC
